name: CSS Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm install -g stylelint stylelint-config-standard
      - name: Analysing the code with stylelint
        run: |
          npx stylelint app/static/style.css
