name: Deploy (Prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/terraform*'

jobs:
  deploy-prod:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      project_id: ${{ vars.GCP_PROJECT_ID }}
      service_name: "python-cloudrun-app"
      region: "us-central1"
    secrets:
      wif_provider: ${{ secrets.GCP_WIF_PROVIDER }}
      wif_service_account: ${{ secrets.GCP_WIF_SA_EMAIL }}
