name: Deploy (Prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/terraform*'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-prod:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      project_id: ${{ vars.GCP_PROJECT_ID }}
      service_name: "python-cloudrun-app"
      region: "us-central1"
      custom_url: "https://calendarsync.billnapier.com"
      wif_provider: "projects/179450231286/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      wif_service_account: "github-actions-sa@calendarsync-napier.iam.gserviceaccount.com"
