name: Terraform Apply Reusable Workflow

# This workflow is designed to be reusable for deploying Terraform changes
# to different environments (e.g., Dev, Prod) by passing in specific inputs.

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
        description: "Environment name (dev or prod)"
      tf_workspace:
        required: true
        type: string
        description: "Terraform workspace"
      project_id:
        required: true
        type: string
        description: "GCP Project ID"
      service_name:
        required: true
        type: string
        description: "Cloud Run Service Name"
      domain_name:
        required: true
        type: string
        description: "Domain Name"
      var_file:
        required: false
        type: string
        description: "Terraform variable file (e.g. dev.tfvars)"
    secrets:
      wif_provider:
        required: true
        description: "Workload Identity Provider"
      wif_service_account:
        required: true
        description: "Workload Identity Service Account"

env:
  TF_VAR_github_owner: ${{ github.repository_owner }}
  TF_VAR_github_repo: ${{ github.event.repository.name }}
  TF_VAR_region: "us-central1"
  TF_VAR_image_tag: "latest"
  TF_VAR_project_id: ${{ inputs.project_id }}
  TF_VAR_service_name: ${{ inputs.service_name }}
  TF_VAR_domain_name: ${{ inputs.domain_name }}

jobs:
  apply:
    name: "Terraform Apply ${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4

      - name: Debug Inputs
        run: |
          echo "Debug: Identifying Environment Variables"
          echo "TF_VAR_project_id: $TF_VAR_project_id"
          echo "Inputs project_id: ${{ inputs.project_id }}"


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.wif_provider }}'
          service_account: '${{ secrets.wif_service_account }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # ratchet:hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Select Workspace
        run: terraform workspace select ${{ inputs.tf_workspace }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: |
          if [ -n "${{ inputs.var_file }}" ]; then
            terraform apply -auto-approve -input=false -var-file=${{ inputs.var_file }}
          else
            terraform apply -auto-approve -input=false
          fi
